# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://takkini.tk'
baseurl: ''
title: 'Sito per takkini'
description: 'solo per veri takkini'
permalink: pretty
logo: "http://www.briarpress.org/?q=system/files/turkey_in_circle.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Su questo sito
  url: /about/
- title: Storie
  url: /blog/

# Footer nav
navigation_footer:
- title: Torna su
  url: "#top"

# Collections
collections:
  posts:
    title: Le nostre avventure
    output: true
    description: "Quello che verrà scritto in seguito è tratto da storie finte"
    feature_text: |
     Libri ( forse ) aperti 
    feature_image: "https://picsum.photos/id/1073/1300/400"
