# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

  #<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

#social
twitter_username:     
github_username:      
linkedin_username:    
google_plus_username:
facebook_username:    yuriy.melnyk
dribbble_username:

# Site settings
url: 'https://takkini.tk'
baseurl: ''
title: 'Sito per takkini'
description: 'solo per veri takkini'
permalink: pretty
logo: "https://mobile-cdn.123rf.com/300wm/jemastock/jemastock1710/jemastock171007426/87998755-progettazione-dell-illustrazione-di-vettore-di-immagine-dell-icona-dell-animale-domestico-del-tacchi.jpg?ver=6"
navigation_header:
- title: Home
  url: /
- title: Su questo sito
  url: /about/
- title: Storie
  url: /blog/

# Footer nav
navigation_footer:
- title: Torna sotto
  url: "#top"

# Collections
collections:
  posts:
    title: Le nostre avventure
    output: true
    description: "Quello che verrà scritto in seguito è tratto da storie finte"
    feature_text: |
     Libri ( forse ) aperti 
    feature_image: "https://picsum.photos/id/1073/1300/400"
